### ISSUE TITLE
You said i should do a issue ticket.

### ISSUE THREAD

**Issue by Cabo1231** [Fastlane-Development/fivepd-discord-whitelist#1]
The Script doesn't work probaly if i want to use it it dont work everyone has acces to fivepd. I want that only the Discord Role has acces to the Duty menu so only they can go to work.

**Comment by GrandpaRex** [comment]
Resolved in [v1.5.0](https://github.com/Fastlane-Development/fivepd-discord-whitelist/releases/tag/v1.5.0)
